In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('/content/Coursera.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3522 entries, 0 to 3521
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Course Name         3522 non-null   object
 1   University          3522 non-null   object
 2   Difficulty Level    3522 non-null   object
 3   Course Rating       3522 non-null   object
 4   Course URL          3522 non-null   object
 5   Course Description  3522 non-null   object
 6   Skills              3522 non-null   object
dtypes: object(7)
memory usage: 192.7+ KB

In [4]:
data.dtypes

Course Name           object
University            object
Difficulty Level      object
Course Rating         object
Course URL            object
Course Description    object
Skills                object
dtype: object

In [5]:
data['Course Name'].value_counts()

Course Name
Google Cloud Platform Fundamentals: Core Infrastructure    8
Python for Data Science and AI                             4
Data Visualization with Python                             4
The Art of Music Production                                4
What is Data Science?                                      4
                                                          ..
Managerial Accounting Fundamentals                         1
Data Visualization                                         1
FinTech Security and Regulation (RegTech)                  1
Using Shiny to Plot Differential Gene Expression           1
How to Finance and Grow Your Startup � Without VC          1
Name: count, Length: 3416, dtype: int64

In [6]:
data['University'].value_counts()

University
Coursera Project Network                      562
University of Illinois at Urbana-Champaign    138
Johns Hopkins University                      110
University of Colorado Boulder                101
University of Michigan                        101
                                             ...
University of Nebraska                          1
Pontificia Universidad Cat�lica de Chile        1
VMware                                          1
E-Learning Development Fund                     1
The World Bank Group                            1
Name: count, Length: 184, dtype: int64

In [7]:
data.columns

Index(['Course Name', 'University', 'Difficulty Level', 'Course Rating',
       'Course URL', 'Course Description', 'Skills'],
      dtype='object')

In [9]:
data = data[['Course Name', 'Difficulty Level','Course URL', 'Course Description', 'Skills']]
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Beginner,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Beginner,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,Advanced,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,Intermediate,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Beginner,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [11]:
data['Course Name'] = data['Course Name'].str.replace(' ',',')
data['Course Name'] = data['Course Name'].str.replace(',,',',')

In [12]:
data['Course Description'] = data['Course Description'].str.replace(' ','')
data['Course Description'] = data['Course Description'].str.replace(':','')
data['Course Description'] = data['Course Description'].str.replace(',','')
data['Course Description'] = data['Course Description'].str.replace(':','')
data['Skills'] = data['Skills'].str.replace('  ','')
data['Skills'] = data['Skills'].str.replace(':', '')
data['Skills'] = data['Skills'].str.replace(',','')

In [13]:
data['tags'] = data['Course Name'] + data['Difficulty Level'] + data['Course Description'] + data['Skills']
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills,tags
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",Beginner,https://www.coursera.org/learn/write-a-feature...,WriteaFullLengthFeatureFilmScriptInthiscoursey...,DramaComedypeeringscreenwritingfilmDocument Re...,"Write,A,Feature,Length,Screenplay,For,Film,Or,..."
1,"Business,Strategy:,Business,Model,Canvas,Analy...",Beginner,https://www.coursera.org/learn/canvas-analysis...,Bytheendofthisguidedprojectyouwillbefluentinid...,Financebusiness planpersona (user experience)b...,"Business,Strategy:,Business,Model,Canvas,Analy..."
2,"Silicon,Thin,Film,Solar,Cells",Advanced,https://www.coursera.org/learn/silicon-thin-fi...,Thiscourseconsistsofageneralpresentationofsola...,chemistryphysicsSolar Energyfilmlambda calculu...,"Silicon,Thin,Film,Solar,CellsAdvancedThiscours..."
3,"Finance,for,Managers",Intermediate,https://www.coursera.org/learn/operational-fin...,Whenitcomestonumbersthereisalwaysmorethanmeets...,accounts receivabledupont analysisanalysisAcco...,"Finance,for,ManagersIntermediateWhenitcomeston..."
4,"Retrieve,Data,using,Single-Table,SQL,Queries",Beginner,https://www.coursera.org/learn/single-table-sq...,Inthiscourseyou�lllearnhowtoeffectivelyretriev...,Data Analysisselect (sql)database management s...,"Retrieve,Data,using,Single-Table,SQL,QueriesBe..."

In [14]:
data['tags'].iloc[1]

'Business,Strategy:,Business,Model,Canvas,Analysis,with,MiroBeginnerBytheendofthisguidedprojectyouwillbefluentinidentifyingandcreatingBusinessModelCanvassolutionsbasedonprevioushigh-levelanalysesandresearchdata.Thiswillenableyoutoidentifyandmaptheelementsrequiredfornewproductsandservices.Furthermoreitisessentialforgeneratingpositiveresultsforyourbusinessventure.Thisguidedprojectisdesignedtoengageandharnessyourvisionaryandexploratoryabilities.YouwilluseprovenmodelsinstrategyandproductdevelopmentwiththeMiroplatformtoexploreandanalyseyourbusinesspropositions.Wewillpracticecriticallyexaminingresultsfrompreviousanalysisandresearchresultsinderivingthevaluesforeachofthebusinessmodelsections.Financebusiness planpersona (user experience)business model canvasPlanningBusinessprojectProduct DevelopmentpresentationStrategy business business-strategy'

In [15]:
data_new = data[['Course Name', 'Course URL', 'tags']]
data_new

,Course Name,Course URL,tags
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",https://www.coursera.org/learn/write-a-feature...,"Write,A,Feature,Length,Screenplay,For,Film,Or,..."
1,"Business,Strategy:,Business,Model,Canvas,Analy...",https://www.coursera.org/learn/canvas-analysis...,"Business,Strategy:,Business,Model,Canvas,Analy..."
2,"Silicon,Thin,Film,Solar,Cells",https://www.coursera.org/learn/silicon-thin-fi...,"Silicon,Thin,Film,Solar,CellsAdvancedThiscours..."
3,"Finance,for,Managers",https://www.coursera.org/learn/operational-fin...,"Finance,for,ManagersIntermediateWhenitcomeston..."
4,"Retrieve,Data,using,Single-Table,SQL,Queries",https://www.coursera.org/learn/single-table-sq...,"Retrieve,Data,using,Single-Table,SQL,QueriesBe..."
...,...,...,...
3517,"Capstone:,Retrieving,Processing,and,Visualizin...",https://www.coursera.org/learn/python-data-vis...,"Capstone:,Retrieving,Processing,and,Visualizin..."
3518,"Patrick,Henry:,Forgotten,Founder",https://www.coursera.org/learn/henry,"Patrick,Henry:,Forgotten,FounderIntermediate�G..."
3519,"Business,intelligence,and,data,analytics:,Gene...",https://www.coursera.org/learn/business-intell...,"Business,intelligence,and,data,analytics:,Gene..."
3520,"Rigid,Body,Dynamics",https://www.coursera.org/learn/rigid-body-dyna...,"Rigid,Body,DynamicsBeginnerThiscourseteachesdy..."
3521,"Architecting,with,Google,Kubernetes,Engine:,Pr...",https://www.coursera.org/learn/deploying-secur...,"Architecting,with,Google,Kubernetes,Engine:,Pr..."

In [16]:
data_new.rename(columns = {'Course Name':'course_name', 'Course URL':'course_url'}, inplace = True)

/tmp/ipython-input-3170102616.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_new.rename(columns = {'Course Name':'course_name', 'Course URL':'course_url'}, inplace = True)

In [17]:
data_new['tags'] = data_new['tags'].apply(lambda x:x.lower())

/tmp/ipython-input-1330164154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_new['tags'] = data_new['tags'].apply(lambda x:x.lower())

In [18]:
data_new.head()

,course_name,course_url,tags
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",https://www.coursera.org/learn/write-a-feature...,"write,a,feature,length,screenplay,for,film,or,..."
1,"Business,Strategy:,Business,Model,Canvas,Analy...",https://www.coursera.org/learn/canvas-analysis...,"business,strategy:,business,model,canvas,analy..."
2,"Silicon,Thin,Film,Solar,Cells",https://www.coursera.org/learn/silicon-thin-fi...,"silicon,thin,film,solar,cellsadvancedthiscours..."
3,"Finance,for,Managers",https://www.coursera.org/learn/operational-fin...,"finance,for,managersintermediatewhenitcomeston..."
4,"Retrieve,Data,using,Single-Table,SQL,Queries",https://www.coursera.org/learn/single-table-sq...,"retrieve,data,using,single-table,sql,queriesbe..."

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vecr = cv.fit_transform(data_new['tags']).toarray()
vars=[0]

In [23]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [24]:
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [25]:
data_new['tags'] = data_new['tags'].apply(stem)
#

/tmp/ipython-input-1861785566.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_new['tags'] = data_new['tags'].apply(stem)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vecr)
#

In [27]:
def recommend(course):
  course_index = data_new[data_new['course_name'] == course].index[0]
  distances = similarity[course_index]
  course_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:7]
  recommended_courses = []
  for i in course_list:
    course_name = data_new.iloc[i[0]].course_name
    course_url = data_new.iloc[i[0]].course_url
    recommended_courses.append({'name':course_name,'url':course_url})
  return recommended_courses
#

In [28]:
data_new.head()

,course_name,course_url,tags
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",https://www.coursera.org/learn/write-a-feature...,"write,a,feature,length,screenplay,for,film,or,..."
1,"Business,Strategy:,Business,Model,Canvas,Analy...",https://www.coursera.org/learn/canvas-analysis...,"business,strategy:,business,model,canvas,analy..."
2,"Silicon,Thin,Film,Solar,Cells",https://www.coursera.org/learn/silicon-thin-fi...,"silicon,thin,film,solar,cellsadvancedthiscours..."
3,"Finance,for,Managers",https://www.coursera.org/learn/operational-fin...,"finance,for,managersintermediatewhenitcomeston..."
4,"Retrieve,Data,using,Single-Table,SQL,Queries",https://www.coursera.org/learn/single-table-sq...,"retrieve,data,using,single-table,sql,queriesbe..."

In [33]:
recommend('Business,Strategy:,Business,Model,Canvas,Analysis,with,Miro')

[{'name': 'Business,Model,Innovation',
  'url': 'https://www.coursera.org/learn/business-model'},
 {'name': 'Digital,Business,Models',
  'url': 'https://www.coursera.org/learn/digital-business-models'},
 {'name': 'Anticipating,Your,Next,Battle,in,Business,and,Beyond',
  'url': 'https://www.coursera.org/learn/anticipate'},
 {'name': 'Planned,Giving',
  'url': 'https://www.coursera.org/learn/planned-giving'},
 {'name': 'Doing,Business,in,Europe',
  'url': 'https://www.coursera.org/learn/doing-business-in-europe'},
 {'name': 'Business,Writing',
  'url': 'https://www.coursera.org/learn/writing-for-business'}]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS
cv

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
sns.set_style('whitegrid')
import matplotlib.pyplot as plt